### ISSUE TITLE
Version 0.3.6 does not work with Umbraco 7.5.11

### ISSUE THREAD

**Issue by msinnott22** [markwemekamp/RankOne-Umbraco-SEO-Tool#18]
I get this issue with the updated version.

I am using Umbraco version 7.5.11.

```
{"Message":"An error has occurred.","ExceptionMessage":"An error occurred when trying to create a controller of type 'DashboardApiController'. Make sure that the controller has a parameterless public constructor.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Could not load file or assembly 'HtmlAgilityPack, Version=1.4.9.5, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)","ExceptionType":"System.IO.FileLoadException","StackTrace":"   at RankOne.Helpers.HtmlHelper..ctor()\r\n   at RankOne.Services.PageAnalysisService..ctor()\r\n   at RankOne.Services.AnalyzeService..ctor()\r\n   at RankOne.Helpers.PageScoreNodeHelper..ctor()\r\n   at RankOne.Services.DashboardDataService..ctor()\r\n   at lambda_method(Closure )\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)"}}
```

Worth locking the nuget package down to Umbraco Versions?

**Comment by markwemekamp** [comment]
Thanks for reporting, the fix code wise should be backward compatible. Looks referencing the new Umbraco version introduced a dependency on a newer version of HtmlAgilityPack. I'll take a look at it

**Comment by markwemekamp** [comment]
I've released a new version with a hotfix on our and nuget

**Comment by msinnott22** [comment]
Hi Mark, 

Apologies with the delay in responding - thanks for releasing a hotfix.  I've since installed this and I am still getting errors:

[RankOne Errors](https://i.imgur.com/sLdXoDc.png)

I haven't changed my version of Umbraco.

[Umbraco Version](https://i.imgur.com/MDTuMJw.png)

Thanks for your help, much appreciated!

**Comment by msinnott22** [comment]
Hi Mark, 

I have gotten it working now. 

Turns out the reference within my Web.config for the HtmlAgilityPack did not update the version of the dependency. 

All fixed and working now!

Thanks for such an awesome add-on.

Mike
